# Generated by Django 6.0.5 on 2026-05-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Image_url',
            field=models.ImageField(upload_to='movie_images/'),
        ),
    ]
