# Generated by Django 6.0.5 on 2026-05-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Image_url',
            new_name='image',
        ),
    ]
